---
title: 'Example: Data Inputs for ModSquad (GOA)'
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Example: Data Inputs for ModSquad (GOA)}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

This script can be used to pull geolocated catch and effort data used to 
calculate model-based indices of abundance using the VAST R package as done by
the GAP ModSquad group for Gulf of Alaska requests. 

```{r, eval = F}
library(gapindex)

## Connect to Oracle. Make sure you are on the NOAA internal network or VPN
sql_channel <- gapindex::get_connected()

## Pull Pacific cod GOA data from 1993:2023
gapindex_data <- gapindex::get_data(survey_set = "GOA",
                                    year_set = 1993:2023,
                                    spp_codes = 21720,
                                    pull_lengths = FALSE,
                                    sql_channel = sql_channel)

## Calculate and zero-fill CPUE using gapindex
gapindex_cpue <- gapindex::calc_cpue(racebase_tables = gapindex_data)

## Format catch and effort data for VAST. Note: The `AreaSwept_km2` field set 
## to 1 when using CPUE in the `Catch_KG` field.
data_geostat <- with(gapindex_cpue, data.frame(Catch_KG = CPUE_KGKM2, 
                                               Year = YEAR,
                                               Vessel = "missing",
                                               AreaSwept_km2 = 1, 
                                               Lat = LATITUDE_DD_START,
                                               Lon = LONGITUDE_DD_START,
                                               Pass = 0) )
```
