---
title: "Example Workflow"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Example Workflow}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r, eval = F}

library(gapindex)

## Connect to Oracle
sql_channel <- gapindex::get_connected()

## Pull data.
gapindex_data <- gapindex::get_data(
  year_set = c(2007, 2009),
  survey_set = "GOA",
  spp_codes = 10261,   
  haul_type = 3,
  abundance_haul = "Y",
  pull_lengths = T,
  sql_channel = sql_channel)

## Fill in zeros and calculate CPUE
cpue <- gapindex::calc_cpue(racebase_tables = gapindex_data)

## Calculate stratum-level biomass, population abundance, mean CPUE and 
## associated variances
biomass_stratum <- gapindex::calc_biomass_stratum(
  racebase_tables = gapindex_data,
  cpue = cpue)

## Calculate aggregated biomass and population abundance across subareas,
## management areas, and regions
biomass_subareas <- gapindex::calc_biomass_subarea(
  racebase_tables = gapindex_data,
  biomass_strata = biomass_stratum)

## Calculate size composition by stratum. See ?gapindex::calc_sizecomp_stratum
## for details on arguments
size_comp_stratum <- gapindex::calc_sizecomp_stratum(
  racebase_tables = gapindex_data,
  racebase_cpue = cpue,
  racebase_stratum_popn = biomass_stratum,
  spatial_level = "stratum",
  fill_NA_method = "AIGOA")

## Calculate aggregated size compositon across subareas, management areas, and
## regions
size_comp_subareas <- gapindex::calc_sizecomp_subarea(
  racebase_tables = gapindex_data,
  size_comps = size_comp_stratum)

## Calculate age-length key. See ?gapindex::calc_ALK for details on arguments
alk <- gapindex::calc_alk(racebase_tables = gapindex_data, 
                          unsex = "all", 
                          global = F)

## Calculate age composition by stratum
age_comp_stratum <- gapindex::calc_agecomp_stratum(
  racebase_tables = gapindex_data, 
  alk = alk,
  size_comp = size_comp_stratum)

## Calculate aggregated age compositon across regions
age_comp_region <- gapindex::calc_agecomp_region(
  racebase_tables = gapindex_data, 
  age_comps_stratum = age_comp_stratum)

```
