#' Bootstrap haul data and return index information
#'
#' @param nboot number of bootstraps
#' @param gapdata an object generated by gapindex::get_data(). It should contain gap data for one species and one region. Multiple years ok.
#' @param gapcpue an object generated by gapinex::calc_cpue().
#'
#' @returns a list of tables (cpue, biomass_subarea, etc) containing bootstrapped results.
#' @export
#'
#' @examples
#'  testdata <- gapindex::get_data(
#'   year_set = c(1996, 1999),
#'   survey_set = c("GOA", "AI", "EBS", "NBS", "BSS")[1],
#'   spp_codes = c(21740, 30060, 10110)[1],
#'   haul_type = 3,
#'   abundance_haul = c("Y", "N")[1],
#'   pull_lengths = TRUE
#' )
#' testcpue <- gapindex::calc_cpue(gapdata = testdata)
#' run_bootstraps(nboot = 5, gapdata = testdata, gapcpue = testcpue)
run_bootstraps <- function(nboot = 5, gapdata, gapcpue) {
  res <- lapply(seq_len(nboot), do_one_bootstrap,
                gapdata = gapdata,
                gapcpue = gapcpue)
  
  list(
    cpue = do.call(rbind, lapply(res, `[[`, "cpue")),
    biomass_stratum = do.call(rbind, lapply(res, `[[`, "biomass_stratum")),
    biomass_subarea = do.call(rbind, lapply(res, `[[`, "biomass_subarea")),
    biomass_total = do.call(rbind, lapply(res, `[[`, "biomass_total"))
  )
}
